name: Test

on:
  workflow_call:
    secrets:
      SONATYPE_USERNAME:
        required: true
        description: 'The SONATYPE username'
      SONATYPE_PASSWORD:
        required: true
        description: 'The SONATYPE password'

jobs:
  build:
    runs-on: k8s-runner-linux
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-maven
        with:
          java-version: '8'
          maven-version: '3.6.3'
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
      - run: mvn verify